project:
  type: website
  output-dir: docs

website:
  title: "Chris Mantegna"
  navbar:
    right:
      - text: "About"
        href: about.qmd
        text: "Research"
        href: https://github.com/ChrisMantegna
        text: "Progress"
        href: https://github.com/ChrisMantegna
        text: "Daily Log"
        href: https://github.com/ChrisMantegna
        text: "Resources"
        href: https://github.com/ChrisMantegna
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: quartz
    css: styles.css

editor: visual

